services:
  jira:
    image: atlassian/jira-software:9.12.2
    container_name: local-jira
    ports:
      - "8080:8080"
    environment:
      - ATL_DB_TYPE=postgresql
      - ATL_JDBC_URL=jdbc:postgresql://jira-db:5432/jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=jira
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Datlassian.plugins.enable.wait=300
    depends_on:
      - jira-db
    volumes:
      - jira-data:/var/atlassian/application-data/jira

  jira-db:
    image: postgres:15
    container_name: jira-db
    environment:
      - POSTGRES_DB=jiradb
      - POSTGRES_USER=jira
      - POSTGRES_PASSWORD=jira
    volumes:
      - jira-db-data:/var/lib/postgresql/data

volumes:
  jira-data:
  jira-db-data:
